# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Space-Rocket
email: contact@romainfrancois.fr
description: "Space-Rocket is a JAVA game made by the IMAC students"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: Alvyre
github_username:  Arctic76

# Build settings
markdown: kramdown
highlighter: rouge
encoding: utf-8
